name: Deploy Node X Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t whoshriyansh/x-webapp-clone-server:latest .

      - name: Push Docker Image
        run: docker push whoshriyansh/x-webapp-clone-server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull whoshriyansh/x-webapp-clone-server:latest

      - name: Remove Old Container
        run: |
          docker stop nodejs-app-container || true
          docker rm nodejs-app-container || true

      - name: Run New Container
        run: |
          docker run -d \
            -p 4000:4000 \
            --name nodejs-app-container \
            -e MONGO_URI=${{ secrets.MONGO_URI }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} \
            -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
            -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} \
            whoshriyansh/x-webapp-clone-server:latest
